export const ROLE_LABELS: Record<string, string> = {
  SystemAdministrator: 'System Administrator',
  AcademicRegistrar: 'Academic Registrar',
  AdminSecretary: 'Admin Secretary',
  'Records Officer': 'Records Officer',
  AdmissionsOfficer: 'Admissions Officer',
  Accountant: 'Accountant',
  AssistantAccountant: 'Assistant Accountant',
  Lecturer: 'Lecturer',
  ExaminationsOfficer: 'Examinations Officer',
  Student: 'Student',
  Secretary: 'Secretary',
  ResidentDirector: 'Resident Director / Human Resource Manager',
  HeadOfDepartment: 'Head of Department',
  Receptionist: 'Receptionist',
  Principal: 'Principal',
  Director: 'Director',
}
