export const ROLES = { systemAdministrator: 'SystemAdministrator', registrar: 'Registrar', academicRegistrar: 'AcademicRegistrar', financeOfficer: 'FinanceOfficer', lecturer: 'Lecturer', examinationsOfficer: 'ExaminationsOfficer', student: 'Student', storeOfficer: 'StoreOfficer', hostelWarden: 'HostelWarden', transportOfficer: 'TransportOfficer', principal: 'Principal', secretary: 'Secretary', residentDirector: 'ResidentDirector', headOfDepartment: 'HeadOfDepartment', assistantPrincipal: 'AssistantPrincipal' } as const
export type InstitutionalRole = typeof ROLES[keyof typeof ROLES]
export function hasAnyRole(userRoles: string[], allowedRoles: readonly string[]): boolean { return allowedRoles.some(role => userRoles.includes(role)) }
export const ADMINISTRATION_ROLES = [ROLES.systemAdministrator, ROLES.registrar] as const
export const ACADEMIC_MANAGEMENT_ROLES = [ROLES.systemAdministrator, ROLES.registrar, ROLES.academicRegistrar] as const
export const FINANCE_MANAGEMENT_ROLES = [ROLES.systemAdministrator, ROLES.financeOfficer] as const
export const EXAMINATION_MANAGEMENT_ROLES = [ROLES.systemAdministrator, ROLES.examinationsOfficer] as const
export const STUDENT_MANAGEMENT_ROLES = [ROLES.systemAdministrator, ROLES.registrar] as const
export const INVENTORY_MANAGEMENT_ROLES = [ROLES.systemAdministrator, ROLES.storeOfficer] as const
export const HOSTEL_MANAGEMENT_ROLES = [ROLES.systemAdministrator, ROLES.hostelWarden] as const
export const TRANSPORT_MANAGEMENT_ROLES = [ROLES.systemAdministrator, ROLES.transportOfficer] as const
export const REPORTS_ROLES = [ROLES.systemAdministrator, ROLES.registrar, ROLES.academicRegistrar, ROLES.financeOfficer, ROLES.examinationsOfficer, ROLES.principal, ROLES.residentDirector, ROLES.assistantPrincipal, ROLES.headOfDepartment, ROLES.secretary] as const
export const COMMUNICATION_ROLES = [ROLES.systemAdministrator, ROLES.registrar, ROLES.academicRegistrar] as const
export const ATTENDANCE_ROLES = [ROLES.systemAdministrator, ROLES.registrar, ROLES.academicRegistrar, ROLES.lecturer] as const
export const STAFF_READ_ROLES = [ROLES.systemAdministrator, ROLES.registrar, ROLES.academicRegistrar, ROLES.lecturer, ROLES.principal, ROLES.residentDirector, ROLES.assistantPrincipal] as const
export const STAFF_MANAGE_ROLES = [ROLES.systemAdministrator, ROLES.registrar, ROLES.principal, ROLES.residentDirector, ROLES.assistantPrincipal] as const
export const LIBRARY_READ_ROLES = [ROLES.systemAdministrator, ROLES.lecturer, ROLES.principal, ROLES.residentDirector] as const
export const LIBRARY_MANAGE_ROLES = [ROLES.systemAdministrator, ROLES.principal, ROLES.residentDirector] as const
export const TIMETABLE_ROLES = [ROLES.systemAdministrator, ROLES.registrar, ROLES.academicRegistrar, ROLES.lecturer, ROLES.principal, ROLES.residentDirector, ROLES.assistantPrincipal] as const
export const ADMISSIONS_ROLES = [ROLES.systemAdministrator, ROLES.registrar, ROLES.academicRegistrar, ROLES.principal, ROLES.residentDirector, ROLES.secretary, ROLES.assistantPrincipal] as const
export const DASHBOARD_ROLES = [ROLES.systemAdministrator, ROLES.registrar, ROLES.academicRegistrar, ROLES.financeOfficer, ROLES.lecturer, ROLES.examinationsOfficer, ROLES.student, ROLES.principal, ROLES.residentDirector, ROLES.assistantPrincipal, ROLES.secretary, ROLES.headOfDepartment] as const
