export const ROLE_LABELS: Record<string, string> = {
  SystemAdministrator: 'System Administrator',
  Registrar: 'Registrar',
  AcademicRegistrar: 'Academic Registrar',
  AdmissionsOfficer: 'Admissions Officer',
  Accountant: 'Accountant',
  AssistantAccountant: 'Assistant Accountant',
  FinanceOfficer: 'Finance Officer',
  Lecturer: 'Lecturer',
  ExaminationsOfficer: 'Examinations Officer',
  Student: 'Student',
  Secretary: 'Secretary',
  ResidentDirector: 'Resident Director / Human Resource Manager',
  HeadOfDepartment: 'Head of Department',
  Receptionist: 'Receptionist',
  Principal: 'Principal',
}
