import { useEffect, useState } from 'react';
import { createStaff, deactivateStaff, listStaff, listLeave, requestLeave, approveLeave, type StaffMember, type LeaveRequest } from '../api/staff';

export function StaffManagement({ canManage }: { canManage: boolean }) {
  const [staff,setStaff]=useState<StaffMember[]>([]); const [error,setError]=useState(''); const [loading,setLoading]=useState(true);
  const [form,setForm]=useState({staffNumber:'',firstName:'',lastName:'',nationalId:'',phoneNumber:'',email:'',employmentType:'Permanent',staffType:'Teaching'});
  const [tab,setTab]=useState<'staff'|'leave'>('staff');
  const [leaveRequests,setLeaveRequests]=useState<LeaveRequest[]>([]);
  const [leaveForm,setLeaveForm]=useState({staffMemberId:'',leaveType:'Annual',startDate:'',endDate:'',reason:''});
  async function load(){setLoading(true);try{setStaff(await listStaff())}catch(e){setError(e instanceof Error?e.message:'Unable to load staff.')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  async function submit(e:React.FormEvent){e.preventDefault();setError('');try{await createStaff(form);setForm({staffNumber:'',firstName:'',lastName:'',nationalId:'',phoneNumber:'',email:'',employmentType:'Permanent',staffType:'Teaching'});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to create staff.')}}
  async function deactivate(id:string){try{await deactivateStaff(id);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to deactivate staff.')}}
  async function loadLeave(){if(!leaveForm.staffMemberId.trim())return;try{setLeaveRequests(await listLeave(leaveForm.staffMemberId.trim()))}catch(e){setError(e instanceof Error?e.message:'Unable to load leave requests.')}}
  async function submitLeave(e:React.FormEvent){e.preventDefault();setError('');try{await requestLeave(leaveForm.staffMemberId.trim(),{...leaveForm,staffMemberId:leaveForm.staffMemberId.trim()});setLeaveForm({staffMemberId:'',leaveType:'Annual',startDate:'',endDate:'',reason:''});await loadLeave()}catch(e){setError(e instanceof Error?e.message:'Unable to request leave.')}}
  async function approveLeaveRequest(id:string,approved:boolean){try{await approveLeave(id,'',approved);await loadLeave()}catch(e){setError(e instanceof Error?e.message:'Unable to approve leave.')}}
  return <section className="panel"><div className="panel-heading"><div><span className="eyebrow">HR</span><h2>Staff Management</h2></div><span className="status">{staff.length} active</span></div>
    <div className="library-tabs" role="tablist"><button role="tab" aria-selected={tab==='staff'} className={tab==='staff'?'active':''} onClick={()=>setTab('staff')}>Staff</button><button role="tab" aria-selected={tab==='leave'} className={tab==='leave'?'active':''} onClick={()=>setTab('leave')}>Leave</button></div>
    {tab==='staff'&&<>{canManage&&<form className="grid-form" onSubmit={submit}><input placeholder="Staff number" value={form.staffNumber} onChange={e=>setForm({...form,staffNumber:e.target.value})} required/><input placeholder="First name" value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})} required/><input placeholder="Last name" value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})} required/><select value={form.staffType} onChange={e=>setForm({...form,staffType:e.target.value})}><option>Teaching</option><option>NonTeaching</option></select><input placeholder="Employment type" value={form.employmentType} onChange={e=>setForm({...form,employmentType:e.target.value})} required/><input placeholder="Phone" value={form.phoneNumber} onChange={e=>setForm({...form,phoneNumber:e.target.value})}/><input placeholder="Email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><button type="submit">Add staff member</button></form>}
    {error&&<div className="error" role="alert">{error}</div>}{loading?<p className="empty">Loading staff…</p>:<div className="table-wrap"><table><thead><tr><th>Staff No.</th><th>Name</th><th>Type</th><th>Employment</th><th>Contact</th>{canManage&&<th>Action</th>}</tr></thead><tbody>{staff.map(s=><tr key={s.id}><td>{s.staffNumber}</td><td>{s.firstName} {s.lastName}</td><td>{s.staffType}</td><td>{s.employmentType}</td><td>{s.email||s.phoneNumber||'—'}</td>{canManage&&<td><button className="secondary-button" onClick={()=>void deactivate(s.id)}>Deactivate</button></td>}</tr>)}</tbody></table></div>}</>}
    {tab==='leave'&&<>{canManage&&<form className="grid-form" onSubmit={submitLeave}><input placeholder="Staff ID" value={leaveForm.staffMemberId} onChange={e=>setLeaveForm({...leaveForm,staffMemberId:e.target.value})} required/><select value={leaveForm.leaveType} onChange={e=>setLeaveForm({...leaveForm,leaveType:e.target.value})}><option>Annual</option><option>Sick</option><option>Maternity</option></select><input placeholder="Start date" type="date" value={leaveForm.startDate} onChange={e=>setLeaveForm({...leaveForm,startDate:e.target.value})} required/><input placeholder="End date" type="date" value={leaveForm.endDate} onChange={e=>setLeaveForm({...leaveForm,endDate:e.target.value})} required/><input placeholder="Reason" value={leaveForm.reason} onChange={e=>setLeaveForm({...leaveForm,reason:e.target.value})} required/><button type="submit">Request Leave</button><button type="button" className="secondary-button" onClick={()=>void loadLeave()}>Load Leave</button></form>}
    {error&&<div className="error" role="alert">{error}</div>}<div className="table-wrap"><table><thead><tr><th>Staff</th><th>Type</th><th>Start</th><th>End</th><th>Reason</th><th>Status</th><th>Action</th></tr></thead><tbody>{leaveRequests.map(lr=><tr key={lr.id}><td>{lr.staffMemberId}</td><td>{lr.leaveType}</td><td>{lr.startDate}</td><td>{lr.endDate}</td><td>{lr.reason}</td><td>{lr.status}</td><td>{lr.status==='Pending'&&<><button className="secondary-button" onClick={()=>void approveLeaveRequest(lr.id,true)}>Approve</button><button className="secondary-button" onClick={()=>void approveLeaveRequest(lr.id,false)}>Reject</button></>}</td></tr>)}</tbody></table></div></>}
  </section>
}

