import { useEffect, useState } from 'react'
import { getAccessToken } from '../api/auth'
const API_BASE_URL = (import.meta.env.VITE_API_BASE_URL as string | undefined)?.replace(/\/$/, '') ?? ''
type Vehicle = { id: string; registrationNumber: string; vehicleType: string; capacity: number; isActive: boolean }
type Route = { id: string; name: string; pickupPoint?: string; destination?: string; fee: number; isActive: boolean }
type Assignment = { id: string; studentId: string; routeId: string; vehicleId: string; startDate: string; status: string; route?: Route; vehicle?: Vehicle }
async function request<T>(path: string, init: RequestInit = {}): Promise<T> { const token = getAccessToken(); const r = await fetch(`${API_BASE_URL}${path}`, { ...init, headers: { Accept: 'application/json', 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) } }); if (!r.ok) { const p = await r.json().catch(() => null) as { message?: string } | null; throw new Error(p?.message ?? `Request failed (${r.status})`) } return r.json() as Promise<T> }
export function TransportManagement({ canManage = true }: { canManage?: boolean }) { const [vehicles, setVehicles] = useState<Vehicle[]>([]); const [routes, setRoutes] = useState<Route[]>([]); const [assignments, setAssignments] = useState<Assignment[]>([]); const [tab, setTab] = useState<'vehicles'|'routes'|'assignments'>('vehicles'); const [registrationNumber, setRegistrationNumber] = useState(''); const [vehicleType, setVehicleType] = useState('Bus'); const [capacity, setCapacity] = useState(30); const [routeName, setRouteName] = useState(''); const [pickupPoint, setPickupPoint] = useState(''); const [destination, setDestination] = useState(''); const [fee, setFee] = useState(0); const [studentId, setStudentId] = useState(''); const [routeId, setRouteId] = useState(''); const [vehicleId, setVehicleId] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
 const load = async () => { setLoading(true); try { const [v, r, a] = await Promise.all([request<Vehicle[]>('/api/transport/vehicles'), request<Route[]>('/api/transport/routes'), request<Assignment[]>('/api/transport/assignments')]); setVehicles(v); setRoutes(r); setAssignments(a) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load transport data.') } finally { setLoading(false) } }; useEffect(() => { void load() }, [])
 async function submit(path: string, body: unknown, success: string) { setError(''); setLoading(true); try { await request(path, { method: 'POST', body: JSON.stringify(body) }); setMessage(success); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Operation failed.') } finally { setLoading(false) } }
 return <section className="panel" aria-label="Transport management"><div className="panel-heading"><div><p className="eyebrow">TRANSPORT</p><h2>Transport Management</h2><p>Manage fleet, routes and student transport assignments.</p></div><button type="button" onClick={() => void load()} disabled={loading}>Refresh</button></div><div className="library-workspace-tabs">{(['vehicles','routes','assignments'] as const).map(x => <button key={x} className={tab===x?'active':''} onClick={() => setTab(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div>{message && <div className="success">{message}</div>}{error && <div className="error" role="alert">{error}</div>}
 {tab==='vehicles' && <><>{canManage && <form className="management-form" onSubmit={e => { e.preventDefault(); void submit('/api/transport/vehicles', { registrationNumber, vehicleType, capacity }, 'Vehicle added.'); setRegistrationNumber('') }}><label>Registration<input value={registrationNumber} onChange={e=>setRegistrationNumber(e.target.value)} required /></label><label>Type<input value={vehicleType} onChange={e=>setVehicleType(e.target.value)} required /></label><label>Capacity<input type="number" min={1} value={capacity} onChange={e=>setCapacity(Number(e.target.value))} /></label><button type="submit" disabled={loading}>Add vehicle</button></form>}</><div className="table-wrap"><table><thead><tr><th>Registration</th><th>Type</th><th>Capacity</th><th>Status</th></tr></thead><tbody>{vehicles.map(v=><tr key={v.id}><td>{v.registrationNumber}</td><td>{v.vehicleType}</td><td>{v.capacity}</td><td>{v.isActive?'Active':'Inactive'}</td></tr>)}</tbody></table></div></>}
 {tab==='routes' && <><>{canManage && <form className="management-form" onSubmit={e => { e.preventDefault(); void submit('/api/transport/routes', { name: routeName, pickupPoint, destination, fee }, 'Route added.'); setRouteName('') }}><label>Route name<input value={routeName} onChange={e=>setRouteName(e.target.value)} required /></label><label>Pickup point<input value={pickupPoint} onChange={e=>setPickupPoint(e.target.value)} /></label><label>Destination<input value={destination} onChange={e=>setDestination(e.target.value)} /></label><label>Fee<input type="number" min={0} step="0.01" value={fee} onChange={e=>setFee(Number(e.target.value))} /></label><button type="submit" disabled={loading}>Add route</button></form>}</><div className="table-wrap"><table><thead><tr><th>Route</th><th>Pickup</th><th>Destination</th><th>Fee</th></tr></thead><tbody>{routes.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.pickupPoint||'—'}</td><td>{r.destination||'—'}</td><td>{r.fee}</td></tr>)}</tbody></table></div></>}
 {tab==='assignments' && <><>{canManage && <form className="management-form" onSubmit={e => { e.preventDefault(); void submit('/api/transport/assignments', { studentId, routeId, vehicleId, startDate: new Date().toISOString().slice(0,10) }, 'Student assigned to transport.'); setStudentId('') }}><label>Student ID<input value={studentId} onChange={e=>setStudentId(e.target.value)} required /></label><label>Route<select value={routeId} onChange={e=>setRouteId(e.target.value)} required><option value="">Select route</option>{routes.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Vehicle<select value={vehicleId} onChange={e=>setVehicleId(e.target.value)} required><option value="">Select vehicle</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.registrationNumber}</option>)}</select></label><button type="submit" disabled={loading}>Assign</button></form>}</><div className="table-wrap"><table><thead><tr><th>Student</th><th>Route</th><th>Vehicle</th><th>Start</th><th>Status</th></tr></thead><tbody>{assignments.map(a=><tr key={a.id}><td>{a.studentId}</td><td>{a.route?.name ?? a.routeId}</td><td>{a.vehicle?.registrationNumber ?? a.vehicleId}</td><td>{a.startDate}</td><td>{a.status}</td></tr>)}</tbody></table></div></>}
 </section> }
