using Microsoft.EntityFrameworkCore;
using SchoolManagement.Domain.Administration;
using SchoolManagement.Domain.Academic;
using SchoolManagement.Domain.Admissions;
using SchoolManagement.Domain.Assessment;
using SchoolManagement.Domain.Attendance;
using SchoolManagement.Domain.Audit;
using SchoolManagement.Domain.Access;
using SchoolManagement.Domain.Calendar;
using SchoolManagement.Domain.Clinical;
using SchoolManagement.Domain.Communication;
using SchoolManagement.Domain.Documents;
using SchoolManagement.Domain.Examinations;
using SchoolManagement.Domain.Finance;
using SchoolManagement.Domain.Identity;
using SchoolManagement.Domain.Library;
using SchoolManagement.Domain.Staff;
using SchoolManagement.Domain.Students;
using SchoolManagement.Domain.Workflows;
using SchoolManagement.Infrastructure.Attendance;
using SchoolManagement.Infrastructure.Assessment;
using SchoolManagement.Infrastructure.Admissions;
using AssessmentTranscriptEntry = SchoolManagement.Domain.Assessment.TranscriptEntry;
using AssessmentAcademicResultSummary = SchoolManagement.Domain.Assessment.AcademicResultSummary;
using AdmissionEntity = SchoolManagement.Domain.Admissions.Admission;
using AcademicStream = SchoolManagement.Domain.Academic.Stream;

namespace SchoolManagement.Infrastructure.Persistence;
public sealed class SchoolManagementDbContext(DbContextOptions<SchoolManagementDbContext> options) : DbContext(options)
{
    public DbSet<User> Users => Set<User>();
    public DbSet<Role> Roles => Set<Role>();
    public DbSet<UserRole> UserRoles => Set<UserRole>();
    public DbSet<InstitutionSettings> InstitutionSettings => Set<InstitutionSettings>();
    public DbSet<Applicant> Applicants => Set<Applicant>();
    public DbSet<Student> Students => Set<Student>();
    public DbSet<StudentGuardian> StudentGuardians => Set<StudentGuardian>();
    public DbSet<Faculty> Faculties => Set<Faculty>();
    public DbSet<Department> Departments => Set<Department>();
    public DbSet<Programme> Programmes => Set<Programme>();
    public DbSet<AcademicYear> AcademicYears => Set<AcademicYear>();
    public DbSet<Semester> Semesters => Set<Semester>();
    public DbSet<Intake> Intakes => Set<Intake>();
    public DbSet<Course> Courses => Set<Course>();
    public DbSet<Curriculum> Curricula => Set<Curriculum>();
    public DbSet<CurriculumCourse> CurriculumCourses => Set<CurriculumCourse>();
    public DbSet<AdmissionEntity> Admissions => Set<AdmissionEntity>();
    public DbSet<AdmissionDecision> AdmissionDecisions => Set<AdmissionDecision>();
    public DbSet<StudentEnrollment> StudentEnrollments => Set<StudentEnrollment>();
    public DbSet<CourseRegistration> CourseRegistrations => Set<CourseRegistration>();
    public DbSet<CourseOffering> CourseOfferings => Set<CourseOffering>();
    public DbSet<TeachingGroup> TeachingGroups => Set<TeachingGroup>();
    public DbSet<TimetableEntry> TimetableEntries => Set<TimetableEntry>();
    public DbSet<AttendanceSession> AttendanceSessions => Set<AttendanceSession>();
    public DbSet<StudentAttendance> StudentAttendances => Set<StudentAttendance>();
    public DbSet<StudentAcademicStatus> StudentAcademicStatuses => Set<StudentAcademicStatus>();
    public DbSet<LearningOutcome> LearningOutcomes => Set<LearningOutcome>();
    public DbSet<AssessmentPlan> AssessmentPlans => Set<AssessmentPlan>();
    public DbSet<StudentAssessment> StudentAssessments => Set<StudentAssessment>();
    public DbSet<AttendanceRecord> AttendanceRecords => Set<AttendanceRecord>();
    public DbSet<AssessmentTranscriptEntry> TranscriptEntries => Set<AssessmentTranscriptEntry>();
    public DbSet<AssessmentAcademicResultSummary> AcademicResultSummaries => Set<AssessmentAcademicResultSummary>();
    public DbSet<Placement> Placements => Set<Placement>();
    public DbSet<StudentPlacement> StudentPlacements => Set<StudentPlacement>();
    public DbSet<Result> Results => Set<Result>();
    public DbSet<StudentPromotion> StudentPromotions => Set<StudentPromotion>();
    public DbSet<FeeStructure> FeeStructures => Set<FeeStructure>();
    public DbSet<FeeItem> FeeItems => Set<FeeItem>();
    public DbSet<StudentInvoice> StudentInvoices => Set<StudentInvoice>();
    public DbSet<StudentFee> StudentFees => Set<StudentFee>();
    public DbSet<Payment> Payments => Set<Payment>();
    public DbSet<PaymentAllocation> PaymentAllocations => Set<PaymentAllocation>();
    public DbSet<PaymentLedgerEntry> PaymentLedgerEntries => Set<PaymentLedgerEntry>();
    public DbSet<ChartOfAccounts> ChartOfAccounts => Set<ChartOfAccounts>();
    public DbSet<Account> Accounts => Set<Account>();
    public DbSet<JournalEntry> JournalEntries => Set<JournalEntry>();
    public DbSet<JournalEntryLine> JournalEntryLines => Set<JournalEntryLine>();
    public DbSet<FiscalPeriod> FiscalPeriods => Set<FiscalPeriod>();
    public DbSet<Vendor> Vendors => Set<Vendor>();
    public DbSet<Bill> Bills => Set<Bill>();
    public DbSet<BillPayment> BillPayments => Set<BillPayment>();
    public DbSet<Budget> Budgets => Set<Budget>();
    public DbSet<BudgetLine> BudgetLines => Set<BudgetLine>();
    public DbSet<BankReconciliation> BankReconciliations => Set<BankReconciliation>();
    public DbSet<BankStatementLine> BankStatementLines => Set<BankStatementLine>();
    public DbSet<CreditNote> CreditNotes => Set<CreditNote>();
    public DbSet<Sponsorship> Sponsorships => Set<Sponsorship>();
    public DbSet<InstalmentPlan> InstalmentPlans => Set<InstalmentPlan>();
    public DbSet<InstalmentPayment> InstalmentPayments => Set<InstalmentPayment>();
    public DbSet<MobileMoneyTransaction> MobileMoneyTransactions => Set<MobileMoneyTransaction>();
    public DbSet<DailyCollection> DailyCollections => Set<DailyCollection>();
    public DbSet<DailyCollectionPayment> DailyCollectionPayments => Set<DailyCollectionPayment>();
    public DbSet<InvoiceNote> InvoiceNotes => Set<InvoiceNote>();
    public DbSet<StaffAdvance> StaffAdvances => Set<StaffAdvance>();
    public DbSet<StaffMember> StaffMembers => Set<StaffMember>();
    public DbSet<PayrollRecord> PayrollRecords => Set<PayrollRecord>();
    public DbSet<LeaveRequest> LeaveRequests => Set<LeaveRequest>();
    public DbSet<TeachingAllocation> TeachingAllocations => Set<TeachingAllocation>();
    public DbSet<LibraryBook> LibraryBooks => Set<LibraryBook>();
    public DbSet<LibraryLoan> LibraryLoans => Set<LibraryLoan>();
    public DbSet<Librarian> Librarians => Set<Librarian>();
    public DbSet<Certificate> Certificates => Set<Certificate>();
    public DbSet<AttendanceQrSession> AttendanceQrSessions => Set<AttendanceQrSession>();
    public DbSet<StudentDocument> StudentDocuments => Set<StudentDocument>();
    public DbSet<WorkflowInstance> WorkflowInstances => Set<WorkflowInstance>();
    public DbSet<WorkflowHistory> WorkflowHistories => Set<WorkflowHistory>();
    public DbSet<Alumni> Alumni => Set<Alumni>();
    public DbSet<CalendarEvent> CalendarEvents => Set<CalendarEvent>();
    public DbSet<GateLog> GateLogs => Set<GateLog>();
    public DbSet<GatePass> GatePasses => Set<GatePass>();
    public DbSet<AuditLog> AuditLogs => Set<AuditLog>();
    public DbSet<AssessmentWeightingProfile> AssessmentWeightingProfiles => Set<AssessmentWeightingProfile>();
    public DbSet<AssessmentWeightingComponent> AssessmentWeightingComponents => Set<AssessmentWeightingComponent>();
    public DbSet<AssessmentPlanWeightingProfile> AssessmentPlanWeightingProfiles => Set<AssessmentPlanWeightingProfile>();
    public DbSet<Notice> Notices => Set<Notice>();
    public DbSet<Conversation> Conversations => Set<Conversation>();
    public DbSet<Message> Messages => Set<Message>();
    public DbSet<AcademicStream> Streams => Set<AcademicStream>();

    protected override void OnModelCreating(ModelBuilder m)
    {
        m.Entity<UserRole>(e =>
        {
            e.HasKey(x => new { x.UserId, x.RoleId });
            e.HasOne<User>().WithMany().HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Cascade);
            e.HasOne<Role>().WithMany().HasForeignKey(x => x.RoleId).OnDelete(DeleteBehavior.Cascade);
        });
        m.Entity<AdmissionDecision>().HasOne<AdmissionEntity>().WithMany().HasForeignKey(x => x.AdmissionId).OnDelete(DeleteBehavior.Cascade);
        m.ApplyConfiguration(new AdmissionsConfiguration());
        m.ApplyConfiguration(new AdmissionDecisionConfiguration());
        AttendanceConfiguration.Apply(m);
        m.ApplyConfiguration(new SchoolManagement.Infrastructure.Certificates.CertificateConfiguration());
        m.ApplyConfiguration(new SchoolManagement.Infrastructure.Documents.StudentDocumentConfiguration());
        m.ApplyConfiguration(new SchoolManagement.Infrastructure.Workflows.WorkflowConfiguration());
        m.ApplyConfiguration(new AssessmentPlanConfiguration());
        m.ApplyConfiguration(new StudentAssessmentConfiguration());
        m.Entity<Payment>(e => { e.HasKey(x => x.Id); e.HasIndex(x => x.ReceiptNumber).IsUnique(); e.Property(x => x.ReceiptNumber).HasMaxLength(50).IsRequired(); e.Property(x => x.Currency).HasMaxLength(10).IsRequired(); e.Property(x => x.PaymentMethod).HasMaxLength(50).IsRequired(); e.Property(x => x.Reference).HasMaxLength(100); e.Property(x => x.Amount).HasPrecision(18, 2); e.HasOne<StudentInvoice>().WithMany().HasForeignKey(x => x.StudentInvoiceId).OnDelete(DeleteBehavior.Restrict); });
        m.Entity<PaymentAllocation>(e => { e.HasKey(x => x.Id); e.HasIndex(x => new { x.PaymentId, x.StudentInvoiceId }).IsUnique(); e.HasOne<Payment>().WithMany(x => x.Allocations).HasForeignKey(x => x.PaymentId).OnDelete(DeleteBehavior.Cascade); e.HasOne<StudentInvoice>().WithMany().HasForeignKey(x => x.StudentInvoiceId).OnDelete(DeleteBehavior.Restrict); e.Property(x => x.AllocatedAmount).HasPrecision(18, 2); e.Property(x => x.Currency).HasMaxLength(10).IsRequired(); e.Property(x => x.Notes).HasMaxLength(500); });
        m.Entity<PaymentLedgerEntry>(e => { e.HasKey(x => x.Id); e.HasIndex(x => new { x.StudentId, x.EntryDate }); e.HasIndex(x => x.PaymentId); e.HasIndex(x => x.StudentInvoiceId); e.Property(x => x.EntryType).HasMaxLength(30).IsRequired(); e.Property(x => x.Description).HasMaxLength(500).IsRequired(); e.Property(x => x.Currency).HasMaxLength(10).IsRequired(); e.Property(x => x.Reference).HasMaxLength(100); e.Property(x => x.Amount).HasPrecision(18, 2); e.HasOne<Student>().WithMany().HasForeignKey(x => x.StudentId).OnDelete(DeleteBehavior.Restrict); e.HasOne<StudentInvoice>().WithMany().HasForeignKey(x => x.StudentInvoiceId).OnDelete(DeleteBehavior.Restrict); e.HasOne<Payment>().WithMany().HasForeignKey(x => x.PaymentId).OnDelete(DeleteBehavior.Restrict); e.HasOne<PaymentAllocation>().WithMany().HasForeignKey(x => x.PaymentAllocationId).OnDelete(DeleteBehavior.Restrict); });
        m.Entity<LibraryBook>(e => { e.HasKey(x => x.Id); e.HasIndex(x => x.Isbn).IsUnique(); e.Property(x => x.Isbn).HasMaxLength(32).IsRequired(); e.Property(x => x.Title).HasMaxLength(250).IsRequired(); e.Property(x => x.Author).HasMaxLength(200).IsRequired(); e.Property(x => x.Publisher).HasMaxLength(200); });
        m.Entity<LibraryLoan>(e => { e.HasKey(x => x.Id); e.HasIndex(x => new { x.StudentId, x.BookId, x.ReturnedAtUtc }); e.HasOne<LibraryBook>().WithMany().HasForeignKey(x => x.BookId).OnDelete(DeleteBehavior.Restrict); e.HasOne<Student>().WithMany().HasForeignKey(x => x.StudentId).OnDelete(DeleteBehavior.Restrict); e.Property(x => x.FineAmount).HasPrecision(18, 2); });
        m.Entity<Librarian>(e => { e.HasKey(x => x.Id); e.HasIndex(x => x.StaffMemberId).IsUnique(); e.Property(x => x.LibraryRole).HasMaxLength(80).IsRequired(); e.HasOne<StaffMember>().WithMany().HasForeignKey(x => x.StaffMemberId).OnDelete(DeleteBehavior.Restrict); });
        m.Entity<AssessmentWeightingProfile>(e => { e.HasKey(x => x.Id); e.Property(x => x.Name).HasMaxLength(160).IsRequired(); e.Property(x => x.RegulatoryBody).HasMaxLength(80); e.Property(x => x.AssessmentModel).HasMaxLength(50); e.HasMany<AssessmentWeightingComponent>().WithOne().HasForeignKey(x => x.AssessmentWeightingProfileId).OnDelete(DeleteBehavior.Cascade); e.HasIndex(x => new { x.Name, x.EffectiveFromUtc }); });
        m.Entity<AssessmentWeightingComponent>(e => { e.HasKey(x => x.Id); e.Property(x => x.Name).HasMaxLength(160).IsRequired(); e.Property(x => x.AssessmentType).HasMaxLength(80).IsRequired(); e.Property(x => x.WeightPercentage).HasPrecision(5, 2); e.Property(x => x.MaximumMark).HasPrecision(8, 2); e.HasIndex(x => new { x.AssessmentWeightingProfileId, x.Name }).IsUnique(); });
        m.Entity<AssessmentPlanWeightingProfile>(e => { e.HasKey(x => new { x.AssessmentPlanId, x.AssessmentWeightingProfileId }); e.HasOne<AssessmentPlan>().WithMany().HasForeignKey(x => x.AssessmentPlanId).OnDelete(DeleteBehavior.Cascade); e.HasOne<AssessmentWeightingProfile>().WithMany().HasForeignKey(x => x.AssessmentWeightingProfileId).OnDelete(DeleteBehavior.Restrict); });
        m.Entity<ChartOfAccounts>(e => { e.HasKey(x => x.Id); e.HasIndex(x => x.Code).IsUnique(); e.Property(x => x.Name).HasMaxLength(200).IsRequired(); e.Property(x => x.Code).HasMaxLength(50).IsRequired(); });
        m.Entity<Account>(e => { e.HasKey(x => x.Id); e.HasIndex(x => new { x.ChartOfAccountsId, x.Code }).IsUnique(); e.Property(x => x.Code).HasMaxLength(50).IsRequired(); e.Property(x => x.Name).HasMaxLength(200).IsRequired(); e.Property(x => x.AccountType).HasMaxLength(50).IsRequired(); e.HasOne<ChartOfAccounts>().WithMany().HasForeignKey(x => x.ChartOfAccountsId).OnDelete(DeleteBehavior.Cascade); });
        m.Entity<JournalEntry>(e => { e.HasKey(x => x.Id); e.HasIndex(x => x.EntryNumber).IsUnique(); e.Property(x => x.EntryNumber).HasMaxLength(50).IsRequired(); e.Property(x => x.Status).HasMaxLength(20).IsRequired(); });
        m.Entity<JournalEntryLine>(e => { e.HasKey(x => x.Id); e.HasOne(x => x.JournalEntry).WithMany(j => j.Lines).HasForeignKey(x => x.JournalEntryId).OnDelete(DeleteBehavior.Cascade); e.HasOne(x => x.Account).WithMany().HasForeignKey(x => x.AccountId).OnDelete(DeleteBehavior.Restrict); e.Property(x => x.Description).HasMaxLength(500); });
        m.Entity<FiscalPeriod>(e => { e.HasKey(x => x.Id); e.HasIndex(x => x.Name).IsUnique(); e.HasIndex(x => new { x.StartDate, x.EndDate }); e.Property(x => x.Name).HasMaxLength(120).IsRequired(); e.Property(x => x.Status).HasMaxLength(20).IsRequired(); e.Property(x => x.ClosedBy).HasMaxLength(200); });
        m.Entity<Vendor>(e => { e.HasKey(x => x.Id); e.HasIndex(x => x.Name).IsUnique(); e.Property(x => x.Name).HasMaxLength(200).IsRequired(); e.Property(x => x.ContactPerson).HasMaxLength(150); e.Property(x => x.Phone).HasMaxLength(50); e.Property(x => x.Email).HasMaxLength(200); });
        m.Entity<Bill>(e => { e.HasKey(x => x.Id); e.HasIndex(x => x.BillNumber).IsUnique(); e.Property(x => x.BillNumber).HasMaxLength(50).IsRequired(); e.Property(x => x.Status).HasMaxLength(20).IsRequired(); e.Property(x => x.Currency).HasMaxLength(10).IsRequired(); e.HasOne<Vendor>().WithMany().HasForeignKey(x => x.VendorId).OnDelete(DeleteBehavior.Restrict); });
        m.Entity<BillPayment>(e => { e.HasKey(x => x.Id); e.HasOne(x => x.Bill).WithMany(b => b.Payments).HasForeignKey(x => x.BillId).OnDelete(DeleteBehavior.Cascade); e.Property(x => x.PaymentMethod).HasMaxLength(50).IsRequired(); e.Property(x => x.Reference).HasMaxLength(100); });
        m.Entity<Budget>(e => { e.HasKey(x => x.Id); e.Property(x => x.Name).HasMaxLength(200).IsRequired(); e.Property(x => x.Currency).HasMaxLength(10).IsRequired(); });
        m.Entity<BudgetLine>(e => { e.HasKey(x => x.Id); e.HasOne(x => x.Budget).WithMany(b => b.Lines).HasForeignKey(x => x.BudgetId).OnDelete(DeleteBehavior.Cascade); e.HasOne<Account>().WithMany().HasForeignKey(x => x.AccountId).OnDelete(DeleteBehavior.Restrict); e.Property(x => x.Category).HasMaxLength(100).IsRequired(); e.Property(x => x.Notes).HasMaxLength(500); });
        m.Entity<BankReconciliation>(e => { e.HasKey(x => x.Id); e.Property(x => x.Status).HasMaxLength(20).IsRequired(); e.Property(x => x.Notes).HasMaxLength(1000); });
        m.Entity<BankStatementLine>(e => { e.HasKey(x => x.Id); e.HasOne<BankReconciliation>().WithMany().HasForeignKey(x => x.BankReconciliationId).OnDelete(DeleteBehavior.Cascade); e.Property(x => x.Description).HasMaxLength(500); e.Property(x => x.TransactionType).HasMaxLength(50).IsRequired(); e.Property(x => x.Reference).HasMaxLength(100); });
        m.Entity<FeeItem>(e => { e.HasKey(x => x.Id); e.Property(x => x.Name).HasMaxLength(160).IsRequired(); e.Property(x => x.FeeType).HasMaxLength(50).IsRequired(); e.Property(x => x.Currency).HasMaxLength(3).IsRequired(); e.Property(x => x.Amount).HasPrecision(18, 2); e.HasIndex(x => new { x.FeeStructureId, x.FeeType }); });
        m.Entity<StudentFee>(e => { e.HasKey(x => x.Id); e.Property(x => x.FeeType).HasMaxLength(50).IsRequired(); e.Property(x => x.Name).HasMaxLength(160).IsRequired(); e.Property(x => x.Amount).HasPrecision(18, 2); e.Property(x => x.PaidAmount).HasPrecision(18, 2); e.Property(x => x.Currency).HasMaxLength(3).IsRequired(); e.Property(x => x.Status).HasMaxLength(30).IsRequired(); e.HasIndex(x => new { x.StudentId, x.StudentInvoiceId, x.FeeType }); e.HasOne<StudentInvoice>().WithMany().HasForeignKey(x => x.StudentInvoiceId).OnDelete(DeleteBehavior.Cascade); e.HasOne<Student>().WithMany().HasForeignKey(x => x.StudentId).OnDelete(DeleteBehavior.Restrict); });
        m.Entity<CreditNote>(e => { e.HasKey(x => x.Id); e.Property(x => x.CreditNoteNumber).HasMaxLength(50).IsRequired(); e.Property(x => x.Reason).HasMaxLength(500).IsRequired(); e.Property(x => x.Status).HasMaxLength(20).IsRequired(); e.HasOne<StudentInvoice>().WithMany().HasForeignKey(x => x.StudentInvoiceId).OnDelete(DeleteBehavior.Restrict); });
        m.Entity<StaffMember>(e => { e.HasKey(x => x.Id); e.Property(x => x.StaffNumber).HasMaxLength(50).IsRequired(); e.Property(x => x.EmploymentType).HasMaxLength(50).IsRequired(); e.Property(x => x.StaffType).HasConversion<string>().HasMaxLength(20).IsRequired(); e.HasIndex(x => x.StaffNumber).IsUnique(); });
        m.Entity<PayrollRecord>(e => { e.HasKey(x => x.Id); e.Property(x => x.Status).HasMaxLength(20).IsRequired(); e.HasOne<StaffMember>().WithMany().HasForeignKey(x => x.StaffMemberId).OnDelete(DeleteBehavior.Restrict); });
        m.Entity<TimetableEntry>(e => { e.HasKey(x => x.Id); e.HasOne<StaffMember>().WithMany().HasForeignKey(x => x.StaffMemberId).OnDelete(DeleteBehavior.Restrict); });
        m.Entity<InstitutionSettings>(e => { e.HasKey(x => x.Id); e.Property(x => x.InstitutionName).HasMaxLength(250).IsRequired(); e.Property(x => x.Abbreviation).HasMaxLength(50); e.Property(x => x.Motto).HasMaxLength(500); e.Property(x => x.Address).HasMaxLength(500); e.Property(x => x.Phone).HasMaxLength(50); e.Property(x => x.Email).HasMaxLength(200); e.Property(x => x.Website).HasMaxLength(200); e.Property(x => x.PostalAddress).HasMaxLength(200); e.Property(x => x.Country).HasMaxLength(100); e.Property(x => x.InstitutionType).HasMaxLength(100); e.Property(x => x.LogoPath).HasMaxLength(500); e.Property(x => x.PrimaryColor).HasMaxLength(20); e.Property(x => x.AccentColor).HasMaxLength(20); e.HasIndex(x => x.IsActive); });
    }
}
