using Microsoft.EntityFrameworkCore;
using SchoolManagement.Domain.Administration;
using SchoolManagement.Domain.Academic;
using SchoolManagement.Domain.Admissions;
using SchoolManagement.Domain.Assessment;
using SchoolManagement.Domain.Attendance;
using SchoolManagement.Domain.Audit;
using SchoolManagement.Domain.Access;
using SchoolManagement.Domain.Calendar;
using SchoolManagement.Domain.Clinical;
using SchoolManagement.Domain.Communication;
using SchoolManagement.Domain.Documents;
using SchoolManagement.Domain.Examinations;
using SchoolManagement.Domain.Finance;
using SchoolManagement.Domain.Identity;
using SchoolManagement.Domain.Library;
using SchoolManagement.Domain.Staff;
using SchoolManagement.Domain.Students;
using SchoolManagement.Domain.Workflows;
using SchoolManagement.Infrastructure.Attendance;
using SchoolManagement.Infrastructure.Assessment;
using SchoolManagement.Infrastructure.Admissions;
using AssessmentTranscriptEntry = SchoolManagement.Domain.Assessment.TranscriptEntry;
using AssessmentAcademicResultSummary = SchoolManagement.Domain.Assessment.AcademicResultSummary;
using AdmissionEntity = SchoolManagement.Domain.Admissions.Admission;
using AcademicStream = SchoolManagement.Domain.Academic.Stream;
