// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace SchoolManagement.Infrastructure.Migrations;

[DbContext(typeof(Persistence.SchoolManagementDbContext))]
[Migration("20260908123000_AddFinanceAuditImmutability")]
partial class AddFinanceAuditImmutability
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // No EF model changes. This migration adds PostgreSQL triggers only.
    }
}
